---
- name: Installs apps common to all environments
  hosts: local
  roles:
    - {role: 'git', tags: 'git'}
    - {role: 'dotfiles', tags: 'dotfiles'}
    - {role: 'tmux', tags: 'tmux'}
    - {role: 'emacs', tags: 'emacs'}
    - {role: 'python', tags: 'python'}
    - {role: 'shellcheck', tags: 'shellcheck'}
