---
- name: Add Python Deadsnakes PPA
  apt_repository:
    repo: ppa:deadsnakes/ppa
  become: yes
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
    - ansible_facts['distribution_major_version'] == '16'

- name: Install Python 3.7
  apt:
    name:
      - python3.7
      - python3.7-venv
      - python3.7-dev
  become: yes
