---
- name: Add the PPA for Emacs 26
  apt_repository:
    repo: ppa:kelleyk/emacs
  become: yes

- name: Install Emacs 26
  apt:
    name: emacs26
    update_cache: yes
  become: yes

- name: Clones the .emacs.d repository
  git:
    dest: "{{ emacs.src_dir }}"
    repo: git@github.com:kmdouglass/.emacs.d.git

- name: Create a symlink to the .emacs.d repo in the home folder
  file:
    path: "{{ ansible_env.HOME }}/{{ emacs.src_dir | basename }}"
    src: "{{ emacs.src_dir }}"
    state: link

- name: Create the user systemd configuration folder if it doesn't exist
  file:
    path: "{{ emacs.service_file_path }}"
    mode: "0755"

- name: Create the emacsd unit file in the user's systemd configuration directory
  template:
    src: emacsd.service.j2
    dest: "{{ emacs.service_file_path }}/emacsd.service"
    mode: "0644"

- name: Launch the emacs server at startup
  systemd:
    name: emacsd
    daemon-reload: yes
    enabled: yes
    state: started
    scope: user

- name: Add the scripts and bin directories if they do not exist
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  loop:
    - bin
    - scripts
    
- name: Add the todo script to the scripts directory for org-capture templates
  copy:
    src: todo.sh
    dest: "{{ ansible_env.HOME }}/scripts"
    mode: "0755"

- name: Create a link to the todo script in the user's home directory
  file:
    path: "{{ ansible_env.HOME }}/bin/todo"
    src: "{{ ansible_env.HOME }}/scripts/todo.sh"
    state: link
