---
- name: Add environment variables for Go to the Bash login profile
  blockinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    block: |
      export PATH="$PATH:{{ go.install_dir }}:$HOME/go/bin"


- name: Install the golint package
  changed_when: no
  command: go get -u golang.org/x/lint/golint
